// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DailyLineChart: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/components/FocusCharts').DailyLineChart
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const LogLevel: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/utils/logger').LogLevel
  const Logger: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/utils/logger').Logger
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const StorageManager: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/utils/storage').StorageManager
  const SyncStorageManager: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/utils/storage').SyncStorageManager
  const WeeklyBarChart: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/components/FocusCharts').WeeklyBarChart
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const playNotificationSound: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/utils/audioPlayer').playNotificationSound
  const playTestSound: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/utils/audioPlayer').playTestSound
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useNotifications: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useNotifications').useNotifications
  const useSettings: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useSettings').useSettings
  const useStatistics: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useStatistics').useStatistics
  const useTaskStatistics: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useTaskStatistics').useTaskStatistics
  const useTasks: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useTasks').useTasks
  const useTheme: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useTheme').useTheme
  const useTimer: typeof import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useTimer').useTimer
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { NotificationState } from 'C:/Users/Aodsp/dev/PomoZen-extension/hooks/useNotifications'
  import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useNotifications')
  // @ts-ignore
  export type { UseTaskStatisticsReturn } from 'C:/Users/Aodsp/dev/PomoZen-extension/hooks/useTaskStatistics'
  import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useTaskStatistics')
  // @ts-ignore
  export type { UseTasksReturn } from 'C:/Users/Aodsp/dev/PomoZen-extension/hooks/useTasks'
  import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useTasks')
  // @ts-ignore
  export type { ThemeModePreference } from 'C:/Users/Aodsp/dev/PomoZen-extension/hooks/useTheme'
  import('C:/Users/Aodsp/dev/PomoZen-extension/hooks/useTheme')
  // @ts-ignore
  export type { LogLevel } from 'C:/Users/Aodsp/dev/PomoZen-extension/utils/logger'
  import('C:/Users/Aodsp/dev/PomoZen-extension/utils/logger')
}
